//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTour.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public string RutAlumno { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Abono { get; set; }
        public string Telefono { get; set; }
        public string Contrasena { get; set; }
        public int IdCurso { get; set; }
        public string RutApoderado { get; set; }
    
        public virtual Apoderado Apoderado { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
