//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTour.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoPrestacionServicio
    {
        public int IdContrato { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public int IdReserva { get; set; }
        public int IdPaquete { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public string Estado { get; set; }
        public string Empleado_Rut { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual PaqueteTuristico PaqueteTuristico { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
