//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTour.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositoCurso
    {
        public int IdDeposito { get; set; }
        public string NumeroCuenta { get; set; }
        public System.DateTime FechaDeposito { get; set; }
        public int Monto { get; set; }
        public int IdActividad { get; set; }
        public string RutRepresentante { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Representante Representante { get; set; }
    }
}
