//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTour.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaqueteTuristico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaqueteTuristico()
        {
            this.ContratoPrestacionServicio = new HashSet<ContratoPrestacionServicio>();
        }
    
        public int IdPaquete { get; set; }
        public string Descripcion { get; set; }
        public int Precio { get; set; }
        public int IdAct { get; set; }
        public int IdSeguro { get; set; }
        public int IdHotel { get; set; }
        public int IdTransporte { get; set; }
    
        public virtual ActividadTuristica ActividadTuristica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPrestacionServicio> ContratoPrestacionServicio { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Seguro Seguro { get; set; }
        public virtual Transporte Transporte { get; set; }
    }
}
